### ISSUE TITLE
Attribute error:  'Share" object has no attribute 'get_info'

### ISSUE THREAD

**Issue by daveroush** [Logicmn/PYX#1]
Your program won't compile.  the error is on line 104:  new_transaction.  Any estimate for a fix?

**Comment by vitteloil** [comment]
It was removed from the latest yahoo-finance github repo. I'm working to fix that right now (edit: I'm not the owner of this project)

**Comment by vitteloil** [comment]
Check this PR it will fix this issue https://github.com/Logicmn/PYX/pull/4

**Comment by daveroush** [comment]
thanks, the fix works.

**Comment by Logicmn** [comment]
Vitteloil is correct, I've merged the fix into the master branch.
